### ISSUE TITLE
EAGAIN and AGAIN and AGAIN and AGAIN

### ISSUE THREAD

**Issue by alexwbai** [extrabacon/python-shell#101]
Hi!

Ok running this is fine:

```
    PythonShell.run('westell-python.py', function (err, results) {
      if (err) throw err;
      // results is an array consisting of messages collected during execution 
      console.log('results: %j', results);
    });
```

If I add the options which are defined as:

```
    var options = {
      args: ['10.0.0.91']
    };
```
and change my code to
```
    PythonShell.run('westell-python.py', options, function (err, results) {
      if (err) throw err;
      // results is an array consisting of messages collected during execution 
      console.log('results: %j', results);
    });
```

I get this:
```
Alexanders-MacBook-Pro:switch_backup_node awitte$ node app.js
TypeError: Cannot read property 'setEncoding' of undefined
    at /Users/awitte/Documents/GitHub/switch_backup_node/node_modules/python-shell/index.js:63:34
    at Array.forEach (native)
    at new PythonShell (/Users/awitte/Documents/GitHub/switch_backup_node/node_modules/python-shell/index.js:61:35)
    at Function.PythonShell.run (/Users/awitte/Documents/GitHub/switch_backup_node/node_modules/python-shell/index.js:159:19)
    at pythonParser (/Users/awitte/Documents/GitHub/switch_backup_node/app.js:51:17)
    at concatIPs.then (/Users/awitte/Documents/GitHub/switch_backup_node/app.js:61:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn python EAGAIN
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Alexanders-MacBook-Pro:switch_backup_node awitte$ 
```

> Alexanders-MacBook-Pro:switch_backup_node awitte$ which python
> /Users/awitte/anaconda3/bin/python

Any thoughts?  All I want to do is send that IP address as an argument to the python script...

**Comment by alexwbai** [comment]
Oh and doing this results in the same error:

```
    var options = {
      args: ['10.0.0.91'],
      pythonPath: '/Users/awitte/anaconda3/bin/python'
    };
```

**Comment by alexwbai** [comment]
Interesting... I had that code above in a for loop.  As soon as I took it out of the for loop it worked fine.  The end options file was just this:

```
    var options = {
      args: ['10.0.0.91']
    };
```
Hope that helps someone else with the same problem...
