### ISSUE TITLE
nodejs cant find python packages

### ISSUE THREAD

**Issue by saikrishna7** [extrabacon/python-shell#104]
The python path is OK as specified in the options

var options = {
  mode: 'text',
  pythonPath: '/usr/local/bin/python3',
  pythonOptions: ['-u']
};

Error: ImportError: No module named requests
    at PythonShell.parseError (/Users/skaf48/Desktop/twitter/firehose-twitter-streaming-nodejs/node_modules/python-shell/index.js:183:17)
    at terminateIfNeeded (/Users/skaf48/Desktop/twitter/firehose-twitter-streaming-nodejs/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/skaf48/Desktop/twitter/firehose-twitter-streaming-nodejs/node_modules/python-shell/index.js:88:9)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
    ----- Python Traceback -----
    File "search_list.py", line 2, in <module>
      import requests

**Comment by JackPickering** [comment]
I have the same error, looks like its been happening for a while, have you found a fix? 

Ive installed my packages using pip install and no luck.

**Comment by JackPickering** [comment]
I managed to fix this issue with a relatively simple work around, basically when you install packages you will install them to a directory names 'site-packages' 

In your main directory this can be found from:
'your-directory/lib/Python3.6/site-packages'

If you copy and paste the files you'd like to run into this folder, and change the script path accordingly, the file will find all imported modules. 

This is because the python shell was looking in the current directory for your packages and not finding them. 

I would suggest that the team allow another option to specify a path contianing installed packages.

**Comment by Almenon** [comment]
@JackPickering sorry for the late response, but I don't really understand the need for a option of a path to installed packages.  Python already knows the path to the site-packages folder.

**Comment by Almenon** [comment]
no response for months, closing.
