### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by renanrosalojasmm** [extrabacon/python-shell#113]
I am getting the following issue:

at PythonShell.parseError (C:\Users\renan.rosa\Documents\Projetos\Biometria Facial\Servidor\node_modules\python-shell\index.js:190:17)
    at terminateIfNeeded (C:\Users\renan.rosa\Documents\Projetos\Biometria Facial\Servidor\node_modules\python-shell\index.js:98:28)
    at ChildProcess.<anonymous> (C:\Users\renan.rosa\Documents\Projetos\Biometria Facial\Servidor\node_modules\python-shell\index.js:88:9)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

This error is very unclear to me, It is not telling the exact problem.

**Comment by Almenon** [comment]
That is not the entire exception log - can you post it in full?

**Comment by ZhipengMei** [comment]
Error Message:
```
/Users/adrian/Documents/testing/nodejs_restapi/api/controllers/s2pController.js:68
        if (err) throw err;

                 ^

Error: Using TensorFlow backend.

    at PythonShell.parseError (/Users/adrian/Documents/testing/nodejs_restapi/node_modules/python-shell/index.js:191:17)
    at terminateIfNeeded (/Users/adrian/Documents/testing/nodejs_restapi/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/adrian/Documents/testing/nodejs_restapi/node_modules/python-shell/index.js:89:9)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

How I use the PythonShell:
```
exports.create_a_task = function(req, res) {
  upload(req, res, function (err) {
      if (err) {
          // An error occurred when uploading
      }
      res.json({
          success: true,
          message: 'Image uploaded!',
          path: req.file.path, 
      });

      // --------------- testing-------------------
      // Python scripts
      var PythonShell = require('python-shell');
      var pyshell = new PythonShell('s2p/ai.py');
      // sends a message to the Python script via stdin
      //pyshell.send(req.file.path);

      pyshell.on('message', function (message) {
        // received a message sent from the Python script (a simple "print" statement)
        console.log(message);
      });

      // end the input stream and allow the process to exit
      pyshell.end(function (err,code,signal) {
        if (err) throw err;
        console.log('finished');
      });
      // -----------------end testing---------------------
  })
};
```

What I am trying to do:
I want to run my python script whenever there is a POST request. Within the python script, I am importing tensorflow, keras and ML models.

**Comment by Almenon** [comment]
no response from OP - maybe sanjayvig's suggestion worked.

Thanks @SanjayVig
