### ISSUE TITLE
PythonShell instance throwing error even though a error handler was assigned

### ISSUE THREAD

**Issue by bary12** [extrabacon/python-shell#123]
I have a PythonShell instance

```javascript
const script = new PythonShell(path.join('server', relPath))
      .on('message', message =>  socket.emit('message', _.escape(message)))
      .on('error', err => socket.emit('error', _.escape(err.message)));
```

I expect this code to not throw an error when the script failed, but it throws

```
events.js:143
      throw err;
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (NameError: name &#39;x&#39; is not defined)
    at Socket.emit (events.js:141:19)
    at Socket.emit (C:\Users\baryl\Documents\projects\javascript\lomda\node_modules\socket.io\lib\socket.js:141:10)et.js:141:10)                                                                                         )
    at PythonShell.on.on.err (C:\Users\baryl\Documents\projects\javascript\lomda\server\shell.js:20:34)
    at PythonShell.emit (events.js:160:13)
    at terminateIfNeeded (C:\Users\baryl\Documents\projects\javascript\lomda\node_modules\python-shell\index.js:111:22)    at ChildProcess.<anonymous> (C:\Users\baryl\Documents\projects\javascript\lomda\node_modules\python-shell\index.js:89:9)
    at ChildProcess.emit (events.js:160:13)    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

I also tried using `.end` instead of `.on('error', ...)` but the same issue occurs. Am I using it right?

**Comment by MikeWeiZhou** [comment]
Had same issue. Errors involving sys.exit() calls and division by zero can't be caught.

**Comment by bary12** [comment]
Actually, my problem wasn't related to this, only that socket throws an error when emitting an error event.
