### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by zerocewl** [extrabacon/python-shell#143]
Usage of pyhton-shell failed with '**Module build failed / Failed to compile**' error.

Angular 6.1.2 + Angular CLI + Python-Shell v1.0.1

From the error message:
**The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).**

Stack trace:
```

ERROR in ./node_modules/python-shell/index.ts
Module build failed: Error: /home/.../node_modules/python-shell/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/home/.../node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
### Workaround:
add to

1.  tsconfig.app.json
```
  "include": [
    "../src/**/*",
    "../node_modules/python-shell/index.ts"
  ],
```

**OR** 
2. tsconfig.json
```
  "include": [
    "src/**/*",
    "node_modules/python-shell/index.ts"
  ],
```

**Comment by Almenon** [comment]
Sorry about that - worked in my library so I assumed it would work in others.  

I included a declaration file - it should work for you now.
