### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Salamit** [extrabacon/python-shell#145]
Hi,

I am getting the following error. I am trying to install python shell to use with Meteor js which uses n
Node js

Could it be that they are not compatible?

```
W20180904-23:32:03.874(9)? (STDERR) /Users/user/Library/Mobile Documents/com~apple~CloudDocs/coding/Courses/meteor-projects/meteorKitchenTest/abeni_1/node_modules/python-shell/index.js:188
W20180904-23:32:03.875(9)? (STDERR)                 return callback(err);
W20180904-23:32:03.875(9)? (STDERR)                        ^
W20180904-23:32:03.875(9)? (STDERR)
W20180904-23:32:03.876(9)? (STDERR) TypeError: callback is not a function
W20180904-23:32:03.876(9)? (STDERR)     at PythonShell._endCallback (/Users/user/Library/Mobile Documents/com~apple~CloudDocs/coding/Courses/meteor-projects/meteorKitchenTest/abeni_1/node_modules/python-shell/index.js:188:24)
W20180904-23:32:03.876(9)? (STDERR)     at terminateIfNeeded (/Users/user/Library/Mobile Documents/com~apple~CloudDocs/coding/Courses/meteor-projects/meteorKitchenTest/abeni_1/node_modules/python-shell/index.js:133:39)
W20180904-23:32:03.876(9)? (STDERR)     at ChildProcess.<anonymous> (/Users/user/Library/Mobile Documents/com~apple~CloudDocs/coding/Courses/meteor-projects/meteorKitchenTest/abeni_1/node_modules/python-shell/index.js:106:13)
W20180904-23:32:03.877(9)? (STDERR)     at emitTwo (events.js:126:13)
W20180904-23:32:03.877(9)? (STDERR)     at ChildProcess.emit (events.js:214:7)
W20180904-23:32:03.877(9)? (STDERR)     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
=> Exited with code: 1
```

**Comment by Almenon** [comment]
How are you calling run? Because what I'm suspecting is that you are passing in the wrong argument for callback.  Callback should be a function.

```typescript
    /**
     * Runs a Python script and returns collected messages
     * @param  {string}   scriptPath   The path to the script to execute
     * @param  {Options}   options  The execution options
     * @param  {Function} callback The callback function to invoke with the script results
     * @return {PythonShell}       The PythonShell instance
     */
    static run(scriptPath, options, callback) {
        let pyshell = new PythonShell(scriptPath, options);
        let output = [];
        return pyshell.on('message', function (message) {
            output.push(message);
        }).end(function (err) {
            if (err)
                return callback(err);
            return callback(null, output.length ? output : null);
        });
    }
```

**Comment by Salamit** [comment]
@Almenon thanks Here is what I ran

PythonShell.runString('x=1+1;print(x)', function (err) {
		if (err) throw err;
		console.log('finished');
	  });

**Comment by Salamit** [comment]
Yes I got that from the documentation. Providing a working sample will help. Thanks.

**Comment by Almenon** [comment]
I fixed the documentation.  Does passing the callback as the third argument work for you now?

**Comment by Salamit** [comment]
That problem is solved. Now have another issue posted here 
https://github.com/extrabacon/python-shell/issues/146#issue-357167581
