### ISSUE TITLE
PythonShell.run is not a function

### ISSUE THREAD

**Issue by Almenon** [extrabacon/python-shell#151]
As @KarthikSamaganam4 said:

PythonShell.run('./script.py', options, function(err, data) {
^

TypeError: PythonShell.run is not a function
at Object. (/Users/ksamaganam/IPFS/document_upload/testScript.js:10:13)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3

Getting this error please help me . I am using python2.7 and have installed latest python-shell module

**Comment by Almenon** [comment]
this error means that PythonShell is undefined.  Are you trying to require python-shell by any chance? Or are you importing it?

**Comment by MongoExpUser** [comment]
I am having the same too problem again. It occurred in **version 1.00,** It was **fixed in version 1.02**. Now it re-occurred again in version **1.0.4**.

It should not matter if you use **require statement** or **import statement**. All Node.js modules generally accepted both statement options for backward compatibility with Pre-ES6 codes.

**Comment by Almenon** [comment]
@MongoExpUser Can you paste your code here please?

**Comment by MongoExpUser** [comment]
See my code below:

var PythonShell  = require('python-shell');   //or let {PythonShell} = require('python-shell')
var pyFile                 = 'myPyFile.py' 
var pyScriptPath      = '/path_to_file/';             
var pyVersionPath   = '/usr/bin/python3.6';    
var pyMode              = 'text';                          
var pyArgs                = ['my_text', 1, 2];              
var options                 = { **mode**: pyMode, **pythonPath**: pyVersionPath, **scriptPath**: pyScriptPath, **args**: pyArgs};

// then: invoke python shell via node.js
var pyShell = PythonShell.run(pyFile, options, function (err) {
           if(err) {console.log(err);} 
});


**pyFile.py simply contains:**

**import** math  

radians = 0.7
print("**Just testing cosine value: "**,  math.cos(radian))

**Comment by Almenon** [comment]
When I use the exact code you gave me with let {PythonShell} = require('python-shell') I do not get the error you are running into.  

[example](https://repl.it/@almenon/OutrageousHightechAtoms)

What version of node are you using? Repl.it uses node v9.7.1

**Comment by MongoExpUser** [comment]
I am using **Node 10.10**. 

It looks like other people are the same issue  based on the comments on another thread...

**Comment by MongoExpUser** [comment]
Almemon,
I just installed version **1.0.6** and this works:

**let {PythonShell} = require('python-shell')**

Thank you very much.

**Comment by fabiom91** [comment]
This works, just change my 'hello.py' with your file:

```python3
var pyshell =  require('python-shell');

  pyshell.PythonShell.run('hello.py', null, function  (err, results)  {
    if  (err)  throw err;
    console.log('hello.py finished.');
    console.log('results', results);
  });
```

**Comment by Salamit** [comment]
Hi, this isn't working for me. I tried the following. Any help is appreciated. 

```
    var pyshell =  require('python-shell');

    pyshell.PythonShell.run('x=1+1;print(x)', null, function  (err)  {
        if  (err)  throw err;
             console.log('script running failed');
    });
```

The result was:
`TypeError: Cannot read property 'run' of undefined`

**Comment by fabiom91** [comment]
> Hi, this isn't working for me. I tried the following. Any help is appreciated.
> 
> ```
>     var pyshell =  require('python-shell');
> 
>     pyshell.PythonShell.run('x=1+1;print(x)', null, function  (err)  {
>         if  (err)  throw err;
>              console.log('script running failed');
>     });
> ```
> 
> The result was:
> `TypeError: Cannot read property 'run' of undefined`

Sorry to hear that, I rechecked and is working to me. This is just a guessing but try reinstalling / updating npm, python shell and or node, see what happens

**Comment by Salamit** [comment]
Thank you! I updated npm, node and python shell and now it works! Thanks a million!
