### ISSUE TITLE
PythonShell is not a constructor (v1.0.4)

### ISSUE THREAD

**Issue by surfaceowl** [extrabacon/python-shell#154]
After upgrading from "python-shell": "0.5.0" to "python-shell": "1.0.4", a previously working link that invokes a python script now returns the error  `"PythonShell is not a constructor"`

The previously working code included:
```
...
const PythonShell = require("python-shell");
...
let pyshell = new PythonShell(script, options);
```

I noticed [that this recent commit](https://github.com/extrabacon/python-shell/commit/ee71a7fec27f6e75d10730c7d44228a09d0c0e67) mentions constructors, but does not seem to change the API.  There is also  this change in the Readme.md
![image](https://user-images.githubusercontent.com/22673372/45728589-67b4ac00-bb7d-11e8-9325-594549f422d6.png)  

... but the examples below in same the Readme appear to be the same as before v1.0.4.
![image](https://user-images.githubusercontent.com/22673372/45728628-9894e100-bb7d-11e8-99ab-592894ac6681.png)

Should I configure something differently, or is this a potential bug?

**Comment by Almenon** [comment]
You need the below code:

```
const {PythonShell} = require("python-shell");
```

Does that work?

**Comment by Almenon** [comment]
I already made a note of it in the github readme but if you confirm that {PythonShell} works I'll release 1.0.5 with updated readme to npm

**Comment by shayfer** [comment]
Adding the curly brackets produces a new error. Thanks for any help!

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at PythonShell.asJson (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:350:21)
    at /home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:302:42
    at Array.forEach (<anonymous>)
    at PythonShell.recieveInternal (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:298:15)
    at PythonShell.receiveStderr (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:282:21)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:100:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
{ Error: ImportError: No module named 'cv2'
    at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:232:21)
    at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:121:32)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:113:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    ----- Python Traceback -----
    File "modules/MMM-Motion-Detection/motiondetection/motiondetection.py", line 19, in <module>
      import cv2
  traceback: 'Traceback (most recent call last):\n  File "modules/MMM-Motion-Detection/motiondetection/motiondetection.py", line 19, in <module>\n    import cv2\nImportError: No module named \'cv2\'\n',
  executable: 'python3',
  options: null,
  script: 'modules/MMM-Motion-Detection/motiondetection/motiondetection.py',
  args: 
   [ '{"useUSBCam":false,"interval":1,"motionStopDelay":120,"detectionThreshold":1000,"turnOffDisplay":true}' ],
  exitCode: 1 }

**Comment by Almenon** [comment]
You got a python error - you tried importing cv2 but it could not be found.

**Comment by shayfer** [comment]
What is the next step do you think? I did a search within the modules/MMM-Motion-Detection/motiondetection folder and there is no cv2. I also tried a search from the root for cv2 files.
Python is installed via sudo apt-get install libopencv-dev python-opencv

Thanks!

**Comment by Almenon** [comment]
What does pip freeze result in? Maybe you need to install cv2 via pip?

**Comment by surfaceowl** [comment]
I think @Almenon has made a good suggestion - seems like cv2 is missing something, perhaps one of the related packages like:  opencv-contrib-python or pip install opencv-contrib-python-headless (per 
https://pypi.org/project/opencv-python/)

Also found this stackoverflow guidance:  https://stackoverflow.com/questions/10417108/what-is-different-between-all-these-opencv-python-interfaces

**Comment by shayfer** [comment]
Good call! I tried installing via pip install opencv-python. That results in Pip fails with Could not find a version that satisfies the requirement ...  I next tried pip install --upgrade pip which did result in a successful installation.  I am getting a slightly different error message now.  I did reboot after the install and I would guess the order of installing PIP after Python shouldn't matter?

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at PythonShell.asJson (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:350:21)
    at /home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:302:42
    at Array.forEach (<anonymous>)
    at PythonShell.recieveInternal (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:298:15)
    at PythonShell.receiveStderr (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:282:21)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:100:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
{ Error: ImportError: No module named 'cv2'
    at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:232:21)
    at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:121:32)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Motion-Detection/node_modules/python-shell/index.js:113:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    ----- Python Traceback -----
    File "modules/MMM-Motion-Detection/motiondetection/motiondetection.py", line 19, in <module>
      import cv2
  traceback: 'Traceback (most recent call last):\n  File "modules/MMM-Motion-Detection/motiondetection/motiondetection.py", line 19, in <module>\n    import cv2\nImportError: No module named \'cv2\'\n',
  executable: 'python3',
  options: null,
  script: 'modules/MMM-Motion-Detection/motiondetection/motiondetection.py',
  args: 
   [ '{"useUSBCam":false,"interval":1,"motionStopDelay":120,"detectionThreshold":1000,"turnOffDisplay":true}' ],
  exitCode: 1 }

**Comment by surfaceowl** [comment]
you have successfully installed cv2, so no further action - I don't see anything that suggests a total fresh installation is needed.  What happens now if you try to run the original script again?  The previous note in this thread about adding [curly braces producing a new error ](https://github.com/extrabacon/python-shell/issues/154#issuecomment-433398921) ...  that was caused by a missing cv2 module, which is now fixed.  Suggest you try running again, without any other changes.

**Comment by shayfer** [comment]
Thanks for everyone’s help and suggestions. I didn’t mean to hijack this thread but I was looking for a way to get this Magic Mirror module to work and posting on the comments yielded no answers. https://github.com/dmcinnes/MMM-Motion-Detection   I did discover and get working a forked project from  https://github.com/rejas/MMM-MotionDetector  I will still try the first module just to see what happens per surfaceowl’s suggestion.

**Comment by Mariaa98** [comment]
`import argparse
def sumOfNum(x, y):
    return x + y

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--x", type=int, required=True)
    parser.add_argument("--y", type=int, required=True)
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    x = args.x
    y = args.y
    total = sumOfNum(x, y)
    print("Total Number is: " , total)

if __name__ == "__main__":
    main()`
I want to run this script through node js but passing parameter gives me error 
this is node js code for run 
`const {PythonShell} = require("python-shell");
var options = {
    mode: 'text',
    args: ['12', '3', '--option=123']
};

PythonShell.run('test.py', options, function (err, results) {
    if (err) throw err;
    // results is an array consisting of messages collected during execution
    console.log('results: %j', results);
});
`
