### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by patrickdundas** [extrabacon/python-shell#169]
Currently running python-shell 1.0.7 on Windows 10 64-Bit.

I have the following python-shell code nested in a javascript function:
```
let pyshell = new PythonShell('test.py');
pyshell.send("Hello World");
```

Upon my javascript function being run, I receive this error:

```
{ Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:713:5)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at PythonShell.send (C:\Users\pdundas\Desktop\Development\bulkrecent-desktop\node_modules\python-shell\index.js:269:20)
    at testLogin (C:\Users\pdundas\Desktop\Development\bulkrecent-desktop\main.js:134:13)
    at EventEmitter.ipcMain.on (C:\Users\pdundas\Desktop\Development\bulkrecent-desktop\main.js:385:5) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
```

I haven't had this error up until the past couple days, so I'm not sure what's changed or why my initial code isn't working. 

My python code is as follows (test.py):
```
print("hello world")
```

Here is my python version string: 
```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
```

**Comment by Almenon** [comment]
Sending hello world is useless if your program is not accepting stdin.  For your python code use print(stdin())

Also I would highly suggest using python 3

**Comment by Almenon** [comment]
closing, no response. Patrick feel free to comment if you have more questions
