### ISSUE TITLE
TypeError: self.stderrParser is not a function

### ISSUE THREAD

**Issue by TahaAsif** [extrabacon/python-shell#178]
I am running a python file using python-shell and got following error:

self.emit(emitType, self.stderrParser(part));
                                         ^

TypeError: self.stderrParser is not a function
    at ../node_modules/python-shell/index.js:310:42
    at Array.forEach (<anonymous>)
    at PythonShell.recieveInternal (../node_modules/python-shell/index.js:306:15)
    at PythonShell.receiveStderr (../node_modules/python-shell/index.js:290:21)
    at Socket.<anonymous> (../node_modules/python-shell/index.js:108:18)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by akzuki** [comment]
Hi,
Anyone having the same problem?
I used python-shell in one of my service classes. Basically wrap it in a Promise and it works fine. But when I tried running unit tests, I got the same error `self.stderrParser is not a function`
Not sure what went wrong here?
