### ISSUE TITLE
StopIteration causes Python-Shell to crash

### ISSUE THREAD

**Issue by AirmanEpic** [extrabacon/python-shell#189]
A stopIteration causes Python-shell to crash. Executing code:
```
ps = require("python-shell")
fs = require("fs");

let options = {
  mode: 'text', // get print results in real-time
  scriptPath: '',
  args: "polyskel-master\\currentfile"
};

polygon = [[40, 40],[40, 310],[520, 310],[520, 40]]
str = ""
for (var i=0; i<polygon.length; i++)
{
	str+= polygon[i][0]+", "+polygon[i][1]
	str+= "\n"
}

fs.writeFileSync("polyskel-master/currentfile",str)

ps.PythonShell.run('polyskel-master/demo_2.py', options, function (err, results) {
  if (err) console.log( err);
  // results is an array consisting of messages collected during execution
  console.log('results: %j', results);
});
```

causes error 
```
Error: RuntimeError: generator raised StopIteration
    at PythonShell.parseError (<dir>\node_modules\python-shell\index.js:246:21)
    at terminateIfNeeded (<dir>\node_modules\python-shell\index.js:129:32)
    at ChildProcess.<anonymous> (<dir>\node_modules\python-shell\index.js:121:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    ----- Python Traceback -----
    File "<dir>\polyskel-master\polyskel.py", line 389, in __iter__
      raise StopIteration
  StopIteration
```

while the same code being run with python:
```python polyskel-master/demo_2.py polyskel-master/currentfile```
succeeds without error.

**Comment by AirmanEpic** [comment]
Update:

The issue was that python-shell was targetting python3 by default. Changing the pythonpath to ``pythonPath: 'C:\\Python27\\python.exe'`` worked perfectly. I didn't think this would be necessary as I only had python2.7 on my machine but apparently it was trying with python3 anyway. Cheers everyone.

**Comment by Almenon** [comment]
You might already be aware, but python 2 is being deprecated by 2020. I would suggest switching to python 3.
