### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by rd16395p** [extrabacon/python-shell#202]
I am trying to run the example found in the readme, and I receive the following error. 

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn py ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn py',
  path: 'py',}

I am using windows 10 with node js, and VS code.

**Comment by Almenon** [comment]
What version of python? is python in your `PATH`?

**Comment by rd16395p** [comment]
3.6 and yes

**Comment by dorakemon** [comment]
I had a similar problem. 
I could solve by this.

https://www.npmjs.com/package/python-shell#running-a-python-script-with-arguments-and-options
