### ISSUE TITLE
Failing test in 0.3.0 from NPM

### ISSUE THREAD

**Issue by zxlin** [extrabacon/python-shell#24]
NPM somehow holds a 0.3.0 version. I don't see that anywhere in the repo, neither does the git commit in package.json on NPM. 

Latest commit also failing dfc6721

`¯\_(ツ)_/¯`

```
  19 passing (214ms)
  1 failing

  1) PythonShell #run(script, options) should run the script and return output data:
     Uncaught TypeError: Cannot read property 'have' of undefined
      at test/test-python-shell.js:43:47
      at null._endCallback (index.js:149:16)
      at ChildProcess.<anonymous> (index.js:99:35)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by extrabacon** [comment]
Whoa, forgot to properly push and tag that release. Thank you for the report!
