### ISSUE TITLE
Python-shell generates

### ISSUE THREAD

**Issue by ptliu** [extrabacon/python-shell#240]
** Problem Description **
Python-shell doesn't seem to correctly recognize that a class can have (type-annotated) members of its own type.

**Python code**
```python
class class_0(object):
  class_0_0:class_0 = None
class_0_0:class_0 = None

class_0_0
print(False)
```
**Javascript code**
```typescript
let pyshell = PythonShell.runString(program, null, function (err, msgs) {
  console.log(">Program:\n" + program + "\n>End Program\n");
  if (err) console.log("ERROR:", err);
  console.log("stdout: ", msgs);
  console.log("finished");
});
```
**Expected behavior**
We expect that this program will properly typecheck and run

**Actual behavior**
Python-shell throws the following error:
```
ERROR: PythonShellError: NameError: name 'class_0' is not defined
    at PythonShell.parseError (/home/ptliu/CSE_231/chocopy-wasm-compiler/node_modules/python-shell/index.js:261:21)
    at terminateIfNeeded (/home/ptliu/CSE_231/chocopy-wasm-compiler/node_modules/python-shell/index.js:144:32)
    at ChildProcess.<anonymous> (/home/ptliu/CSE_231/chocopy-wasm-compiler/node_modules/python-shell/index.js:136:13)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    ----- Python Traceback -----
    File "/tmp/pythonShellFile8030112706.py", line 1, in <module>
      class class_0(object):
    File "/tmp/pythonShellFile8030112706.py", line 2, in class_0
      class_0_0:class_0 = None {
  traceback: 'Traceback (most recent call last):\n' +
    '  File "/tmp/pythonShellFile8030112706.py", line 1, in <module>\n' +
    '    class class_0(object):\n' +
    '  File "/tmp/pythonShellFile8030112706.py", line 2, in class_0\n' +
    '    class_0_0:class_0 = None\n' +
    "NameError: name 'class_0' is not defined\n",
  executable: 'python3',
  options: null,
  script: '/tmp/pythonShellFile8030112706.py',
  args: null,
  exitCode: 1
}
stdout:  null
finished
```
**Other Information (please complete the following information):**
 - OS: Ubuntu 20.04 and Windows 10 WSL 2, reproduced on both
 - Python Version [e.g. 3.6] 3.6.9, 3.85, reproduced on both
 - Node Version [e.g. 12] 10.19.0, 14.6.0, reproduced on both

**Additional context**
This issue was discovered in the context of autogenerating programs.

**Comment by Almenon** [comment]
This is a bug with your python code, not with pythons-shell.

```
C:\dev\python-shell>python a.py
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    class class_0(object):
  File "a.py", line 2, in class_0
    class_0_0:class_0 = None
NameError: name 'class_0' is not defined
```
