### ISSUE TITLE
Can't run any python code

### ISSUE THREAD

**Issue by Edward205** [extrabacon/python-shell#252]
**Describe the bug**
python-shell doesen't execute any python code and returns the same error every time

**Python code**
`print('test')`

**Javascript code**
```
const PythonShell = require('python-shell').PythonShell;

PythonShell.run('my_script.py', null, function (err) {
  if (err) throw err;
  console.log('finished');
});
```

**Expected behavior**
python-shell run code and print 'test' in console

**Actual behavior**
Error in console:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on PythonShell instance at:
    at ChildProcess.<anonymous> (C:\Users\edwar\Desktop\gpt revolt\node_modules\python-shell\index.js:177:18)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn python',
  path: 'python',
  spawnargs: [ 'script.py' ]
}
```

**Other Information (please complete the following information):**
 - Windows 10
 - Python Version 3.9
 - Node Version 12.18.3

**Additional context**
I don't know what to do, please ask for more details about my pc if needed. Thanks

**Comment by Almenon** [comment]
Google ENOENT. Also do a search for ENOENT in GitHub issues. Let me know if you need more help.

**Comment by Edward205** [comment]
Thanks. I searched for the whole error not for just "ENOENT"
The problem was that my python was "py" in path but when i renamed it to "python" it worked. I hope i explained good.

**Comment by Almenon** [comment]
Good job, nice find! :)
