### ISSUE TITLE
PythonShell is not a constructor

### ISSUE THREAD

**Issue by bbartling** [extrabacon/python-shell#261]
**Describe the bug**
Error in Node Red when I try to run it `PythonShell is not a constructor.` Same title as this other Git Issue:
https://github.com/extrabacon/python-shell/issues/154

**Python code**
Relevant Python code to reproduce the problem. This [code below](https://github.com/VOLTTRON/volttron/tree/main/examples/NodeRed) is part of the Python IoT framework called VOLTTRON that has a Node Red Connector. 

```
from datetime import datetime
import os
import sys


import gevent

from volttron.platform.messaging import headers as headers_mod
from volttron.platform.vip.agent import Agent, PubSub, Core
from volttron.platform.agent import utils
from volttron.platform.scheduling import periodic
from volttron.platform import jsonapi

from settings import topic_prefixes_to_watch, heartbeat_period, agent_kwargs


class NodeRedSubscriber(Agent):

    def onmessage(self, peer, sender, bus, topic, headers, message):
        d = {'topic': topic,
             'headers': headers,
             'message': message}
        sys.stdout.write(jsonapi.dumps(d)+'\n')
        sys.stdout.flush()

    @Core.receiver('onstart')
    def onstart(self, sender, **kwargs):
        for prefix in topic_prefixes_to_watch:
            self.vip.pubsub.subscribe(peer='pubsub', prefix=prefix, callback=self.onmessage).get(timeout=10)

    # Demonstrate periodic decorator and settings access
    @Core.schedule(periodic(heartbeat_period))
    def publish_heartbeat(self):
        now = utils.format_timestamp(datetime.utcnow())
        headers = {
            headers_mod.CONTENT_TYPE: headers_mod.CONTENT_TYPE.PLAIN_TEXT,
            headers_mod.DATE: now,
            headers_mod.TIMESTAMP: now
        }
        result = self.vip.pubsub.publish('pubsub', 'heartbeat/NodeRedSubscriber', headers, now)
        result.get(timeout=10)


if  __name__ == '__main__':
    try:
        # If stdout is a pipe, re-open it line buffered
        if utils.isapipe(sys.stdout):
            # Hold a reference to the previous file object so it doesn't
            # get garbage collected and close the underlying descriptor.
            stdout = sys.stdout
            sys.stdout = os.fdopen(stdout.fileno(), 'w', 1)

        agent = NodeRedSubscriber(identity='NodeRedSubscriber', **agent_kwargs)
        task = gevent.spawn(agent.core.run)

        try:
            task.join()
        finally:
            task.kill()

    except KeyboardInterrupt:
        pass
```

**Javascript code**

```
module.exports = function(RED) {
    // Set these variables to be valid file paths
    var volttron_env = '';
    var volttron_home = '';
    var python_path = '';

    function VolttronInputNode(config) {
        RED.nodes.createNode(this,config);
        var node = this;
        var pyshell = null;
        this.on('close', function(done) {
            setTimeout(function() {
                /* do some asynchronous cleanup before calling done */
                if (pyshell && !pyshell.terminated && pyshell.childProcess)
                    pyshell.childProcess.kill('SIGINT');
                done();
            });
        });
        setTimeout(function() {
            var PythonShell = require('python-shell');
            process.env['VIRTUAL_ENV'] = volttron_env;
            process.env['VOLTTRON_HOME'] = volttron_home;
            var options = {
                mode: 'json',
                pythonPath: python_path,
                scriptPath: __dirname,
            };
            var path = require('path');
            node.warn(__dirname);
            var scriptName = 'node_red_subscriber.py';
            var scriptPath = path.resolve(__dirname, scriptName);
            node.warn(scriptPath);
            pyshell = new PythonShell(scriptName, options);

            pyshell.on('message', function (data) {
                msg = {};
                msg.topic = node.name;
                msg.payload = data;
                node.send(msg);
            });

            pyshell.end(function (err) {
                node.error(err);
            });

        });
    }
    RED.nodes.registerType("volttron-input", VolttronInputNode);

    function VolttronOutputNode(config) {
        RED.nodes.createNode(this,config);
        var node = this;
        this.on('close', function(done) {
            setTimeout(function() { /* do some asynchronous cleanup before calling done */ done(); });
        });
        this.on("input", function (msg) {
            setTimeout(function() { // send asynchronously
                var PythonShell = require('python-shell');
                process.env['VIRTUAL_ENV'] = volttron_env;
                process.env['VOLTTRON_HOME'] = volttron_home;
                var options = {
                    mode: 'json',
                    pythonPath: python_path,
                    scriptPath: __dirname,
                    args: [msg.payload.topic, msg.payload.data]
                };
                var path = require('path');
                var scriptName = 'node_red_publisher.py';
                var scriptPath = path.resolve(__dirname, scriptName);
                PythonShell.run(scriptName, options, function(err, result) {
                    if (err) node.error(err);
                    if (result) node.warn(result);
                });
            });

        });
    }
    RED.nodes.registerType("volttron-output",VolttronOutputNode);

}
```

**Expected behavior**
I think there would be data exchange from Python to javascript via stdin and stdout?

**Actual behavior**
PythonShell is not a constructor

**Other Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version is 3.8
 - Node Version Node.js v12.22.7

**Additional context**
Traceback:

```
13 Dec 10:07:36 - [warn] [volttron-input:0df0e1663496fe19] /home/ben/.node-red/node_modules/volttron
13 Dec 10:07:36 - [warn] [volttron-input:0df0e1663496fe19] /home/ben/.node-red/node_modules/volttron/node_red_subscriber.py
13 Dec 10:07:36 - [red] Uncaught Exception:
13 Dec 10:07:36 - TypeError: PythonShell is not a constructor
    at Timeout._onTimeout (/home/ben/.node-red/node_modules/volttron/volttron.js:33:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by bbartling** [comment]
This process is abandoned.
