### ISSUE TITLE
How to avoid the error when I import keras

### ISSUE THREAD

**Issue by yuetianluo** [extrabacon/python-shell#53]
Hi~ 

I came across problem in the #52 again, this time I wanted to import keras in my python program. And when I import the keras, it will show 'Using Theano backend' and it will be regarded as an error. @extrabacon has mentioned in #52 that to override PythonShell.prototype.parseError, could you @extrabacon explain more details about how to implement that. Also is there any other method? such as avoid kears from printing that, because I do not want to lose python traceback
Thank you ahead for your help!

`/Users/luoyuetian/Desktop/junior/summerproject/course_recommendation_interface/api/controllers/NextcourseController.js:30
          if (err) throw err;
                   ^

Error: Using Theano backend.

```
at PythonShell.parseError (/Users/luoyuetian/Desktop/junior/summerproject/course_recommendation_interface/node_modules/python-shell/index.js:190:17)
at terminateIfNeeded (/Users/luoyuetian/Desktop/junior/summerproject/course_recommendation_interface/node_modules/python-shell/index.js:98:28)
at ChildProcess.<anonymous> (/Users/luoyuetian/Desktop/junior/summerproject/course_recommendation_interface/node_modules/python-shell/index.js:88:9)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`
```

**Comment by extrabacon** [comment]
I just tried this approach in a quick example and unfortunately it does not work. The overridden method is expected to return an error, it cannot suppress it at this point. If logging cannot be suppressed, we would need PythonShell to explicitly ignore output from stderr, which is not supported at this point.

**Comment by yuetianluo** [comment]
Thank you @extrabacon . I have tried method in https://github.com/fchollet/keras/issues/3614. I suppressed the stderr and stdout of python, it works now
