### ISSUE TITLE
Throwing error while running python script

### ISSUE THREAD

**Issue by Anandharaj** [extrabacon/python-shell#55]
at PythonShell.parseError (/home/anandharajan/Anand_Data/Automation Client/Server Files/node_modules/python-shell/index.js:190:17)
    at terminateIfNeeded (/home/anandharajan/Anand_Data/Automation Client/Server Files/node_modules/python-shell/index.js:98:28)
    at Socket.<anonymous> (/home/anandharajan/Anand_Data/Automation Client/Server Files/node_modules/python-shell/index.js:83:9)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by extrabacon** [comment]
No error message and just a stack trace?
