### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by jjhesk** [extrabacon/python-shell#58]
spawn EACCES

Error: spawn EACCES
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at new PythonShell (.../node_modules/python-shell/index.js:59:25)
    at Function.PythonShell.run (.../node_modules/python-shell/index.js:159:19)
...

What is the proper fix for this?

`PythonShell` is called from `project/path` and the py script is executed from the `bin` folder from the usr/local/bin

**Comment by jjhesk** [comment]
Its the path issue. I wasnt pointer the right path to the scriptPath
