### ISSUE TITLE
How the python script receive the options arguments

### ISSUE THREAD

**Issue by vn425282** [extrabacon/python-shell#64]
Sorry for my bad English. I would like to know How the python script receive the options arguments
I'm trying to write some code like this :

```
 var options = {
	  username: 'vn425282',
	  password: 'd91b4aff0e301711a30e54af6e3ad16e'
 };

 PythonShell.run('/cloud/connect_db.py', options, function (err, results) {
      res.success(results);
      res.success(err);
      if (err) throw err;
```

and my connect_db.py like this 

```
import sys

uname = str(sys.argv[1])
password = str(sys.argv[2])
print uname
```

and I got the error like bellow

```
`  Result: {"traceback":"Traceback (most recent call last):\n  File \"cloud/connect_db.py\", line 5, in <module>\n    uname = str(sys.argv[1])\nIndexError: list index out of range\n","executable":"python","options":null,"script":"cloud/connect_db.py","args":null,"exitCode":1} functionName=login, , user=undefined
/root/parse-server-example/node_modules/parse-server/lib/ParseServer.js:401
            throw err;
            ^

Error: IndexError: list index out of range
    at PythonShell.parseError (/root/parse-server-example/node_modules/python-shell/index.js:183:17)
    at terminateIfNeeded (/root/parse-server-example/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/root/parse-server-example/node_modules/python-shell/index.js:88:9)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    ----- Python Traceback -----
    File "cloud/connect_db.py", line 5, in <module>
      uname = str(sys.argv[1])
`
```

please help me

**Comment by vn425282** [comment]
I read clearly the document and found the solution for that , thanks you !

**Comment by CLWcynthia** [comment]
can you tell me,how to slove this problem? i want to use python-shell send argument to python script,but i don`t know what the python script write.
