### ISSUE TITLE
self.parseError is not a function

### ISSUE THREAD

**Issue by Phyks** [extrabacon/python-shell#65]
Hi,

I had the exact same issue as #38 which I solved using the `scriptPath` option. Still, it was hard to diagnose it as I was not getting any other output than "ECONNRESET" and:
```
TypeError: self.parseError is not a function
    at terminateIfNeeded (.../node_modules/python-shell/index.js:99:28)
    at Socket.<anonymous> (.../node_modules/python-shell/index.js:78:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Not sure why `self.parseError` was not defined on `Python-shell`. I am running my script through `npm` and `babel-node`.

Thanks

_Note_: When my Python script is loaded and an error occurs in the Python code, the `parseError` function works fine.

**Comment by Almenon** [comment]
#38 is fixed and I'm presuming phyks has fixed on or moved on from this problem already - closing.  Phyks feel free to comment if you still have this problem although I can't guarantee I will have time to look into the issue.
