### ISSUE TITLE
Virtual Enviroment

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [extrabacon/python-shell#71]
Is it possible to launch a virtual environment for the python script to run in?

**Comment by extrabacon** [comment]
No, you will need to setup the virtual environment first.

**Comment by BebeSparkelSparkel** [comment]
ok if I start my node app in my python virtual environment (virtualenv==15.0.3) the python scripts launched cannot find the packages of the virtual environment 
```
MacBook-Air:demo_website williamrusnack$ source ~/Documents/virtualenv_all/nesting/bin/activate
(nesting) MacBook-Air:demo_website williamrusnack$ sudo node ./bin/www  

pyshell.on
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ImportError: No module named 'Dispenser'
    at PythonShell.parseError (/Users/williamrusnack/Documents/node_stuff/demo_website/node_modules/python-shell/index.js:166:17)
    at ChildProcess.<anonymous> (/Users/williamrusnack/Documents/node_stuff/demo_website/node_modules/python-shell/index.js:80:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    ----- Python Traceback -----
    File "/Users/williamrusnack/Documents/nesting/main_just_nest.py", line 2, in <module>
      from nesting_methods import nesting_methods
    File "/Users/williamrusnack/Documents/nesting/nesting_methods.py", line 21, in <module>
      from Dispenser import Dispenser, Counter  # dispenses objects in order or at random

(nesting) MacBook-Air:demo_website williamrusnack$ python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Dispenser
>>> 
```

**Comment by zoellner** [comment]
why are your running node as root? i.e. why do you use `sudeo node` instead of just `node`?
that basically exits your virtualenv

**Comment by BebeSparkelSparkel** [comment]
I have figured this out. I just need to call the python exe in the virtual env directory.

**Comment by ManabBala** [comment]
> I have figured this out. I just need to call the python exe in the virtual env directory.
@BebeSparkelSparkel 
how did you do that? i am on windows. can you guide me?
