### ISSUE TITLE
setInterval() with python-shell

### ISSUE THREAD

**Issue by lee-pham** [extrabacon/python-shell#83]
I want to read data from a simple one line python script.
```
print('hello')
```

When I run
```
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');

function printpy() {
    pyshell.on('message', function (message) {
               console.log(message)
    });
}

printpy()
printpy()
printpy()
```

I receive

```
hello
hello
hello
```

However, when I try to place the function inside setInterval,
```
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');

function printpy() {
    pyshell.on('message', function (message) {
               console.log(message)
    });
}

setInterval(printpy, 1000)
```
The code no longer is printing to the console. And eventually I get
```
(node) warning: possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at go [as _repeat] (/Users/leepham/Desktop/shell/pyshell.js:8:9)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```
What is the best way to loop python-shell so I can access a simple python script that returns a new value?

(the actual python script would look like
```
import sensor
print(sensor.getvalue())
```
)

**Comment by extrabacon** [comment]
This code registers an event handler over and over. The handler should be registered only once.

**Comment by lee-pham** [comment]
Solution found by doing
```
var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');

pyshell.on('message', function (message) {
           console.log(message)
});
```
Then
```
import time
import sys
while True:
    print('hi')
    sys.stdout.flush()
    time.sleep(1)
```
