### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by Mica7812** [extrabacon/python-shell#87]
Hi,

I get this error when trying to call python 3:
`var PythonShell = require('python-shell');

var options = {
  pythonPath:'/usr/lib/python3/',
  args: ['barisozcan.txt']
};`

`internal/child_process.js:309
    throw errnoException(err, 'spawn');
    ^
Error: spawn EACCES
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:309:11)
    at exports.spawn (child_process.js:362:9)
    at new PythonShell (/home/mica/Documents/Web/node_modules/python-shell/index.js:59:25)
    at Function.PythonShell.run (/home/mica/Documents/Web/node_modules/python-shell/index.js:159:19)
    at Object.<anonymous> (/home/mica/Documents/Web/app.js:347:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
`

I am using node.js

What am I supposed to do?

**Comment by fractalDimension** [comment]
Try `'/usr/bin/python3/'` instead of `'/usr/lib/python3/'` in your `pythonPath:` property. It's looking for the executable and you have it pointed at a directory.

**Comment by funilrys** [comment]
Wouldn't it be better to search for `/usr/bin/env python` ?

**Comment by fractalDimension** [comment]
@funilrys hmm I'm not sure. Idk which version it would point to if he had both python 2 and 3 installed.

**Comment by funilrys** [comment]
@fractalDimension if you need python 2 you can trye `/usr/bin/env python2`. 

If both are installed:
```
/usr/bin/env python ==> python3
/usr/bin/env python2 ==> python2
```

**Comment by mohamedScikitLearn** [comment]
try to get the path to your Python3 by typing in terminal:
`which python3` 

Then paste that path to your code.

**Comment by funilrys** [comment]
Well if python is installed what I proposed will always provide the right interpreter...
